### ISSUE TITLE
Individuals should not be able to join events that happened in the past

### ISSUE THREAD

**Issue by meganlee18** [zendesk/volunteer_portal#120]
At the moment, individuals can still click to join events that took place in the past. This potentially distorts the total of volunteering hours of participation for that individual.

Ideally, the 'click to join' button should be greyed out and be inactive for all individuals after time has passed.

**Comment by danielbreves** [comment]
I wonder if some volunteers may forget to join initially and may want the ability to sign up later? But agree maybe it could be greyed out after a certain period, or maybe we can restrict it so only admins can add people later.

cc @azaiszen

**Comment by azaiszen** [comment]
closing this issue in lieu of employees making mistakes and needing to sign in after - also if needed we can now remove individuals from events too.
