### ISSUE TITLE
As an Admin, I should get a notification that there is a new 'individual event' that needs to be approved. Ideally a ticket would be created in volunteerhelp.zendesk.com and there would be an approve/decline button in the ticket window

### ISSUE THREAD

**Issue by samzx** [zendesk/volunteer_portal#125]
Progress: https://github.com/zendesk/volunteer_portal/compare/sxie/%23125-create-zendesk-ticket

**Comment by azaiszen** [comment]
would like to add an auto-approve feature in lieu of this... however the auto-approve would need to be turned off too, need to create a toggle

**Comment by samzx** [comment]
Instead, we might make a feature to "select all" and then "actions" → "approve".

**Comment by samzx** [comment]
Partially solves this issue: https://github.com/zendesk/volunteer_portal/pull/160
Feel free to re-open if required.
