### ISSUE TITLE
Irrelevant pop ups on Dashboard page when clicking avatar

### ISSUE THREAD

**Issue by xuebingli** [zendesk/volunteer_portal#152]
This is a hilarious bug (possibly) introduced by #87 

![](https://cl.ly/27f9be2cd921/Screen%20Recording%202019-04-10%20at%2012.53%20pm.gif)

**Comment by sunstryder** [comment]
This happpens on pages where the `<NamedAvatar>` component appears in both the top right nav and also in the page body

**Comment by ThuTrinh** [comment]
This is no longer an issue since we replaced the profile component.
