### ISSUE TITLE
Add "duplicate event" feature to streamline event creation

### ISSUE THREAD

**Issue by echinveeraphan-zen** [zendesk/volunteer_portal#16]
Currently, we have a table for storing some reoccurring events in the "event_groups" table. 
The events table also contains a column "event_groups_id" which we can use to relate the two. 

We need a way for an admin to mark an event as "reoccurring", creating a record in the events_group_table, with the title as the title of the event. Then update that new event_group_id in that event's record.

**Comment by azaiszen** [comment]
would like to add a duplicate button to events, rather than reoccurring
