### ISSUE TITLE
i18n volunteer portal

### ISSUE THREAD

**Issue by samzx** [zendesk/volunteer_portal#167]
First step, Japanese! 🎉 

~https://github.com/zendesk/client-i18n-tools~
We'll have to use an open source client i18n tool, and write middlewares to make it compatible with existing Zendesk infrastructure to generate the translations. Once generated, we can serve the locales appropriately.

**Comment by kennethc** [comment]
i18n related features are being planned and tracked separately in https://github.com/zendesk/volunteer_portal/projects/15
