### ISSUE TITLE
Volunteer link is no longer active

### ISSUE THREAD

**Issue by nick-f** [zendesk/volunteer_portal#171]
This link is broken:
<img width="840" alt="slack" src="https://user-images.githubusercontent.com/754567/60321607-a73bde80-99c0-11e9-8023-c99fda7feece.png">

![image](https://user-images.githubusercontent.com/754567/60321485-42808400-99c0-11e9-8c37-a3e0e692f247.png)

**Comment by xuebingli** [comment]
Thanks for reporting this, Nick! I'm not sure if the public slack instance is still going. Maybe @adam-hart or @roseleaf could shed more light.

**Comment by roseleaf** [comment]
Huh. The link must have expired I guess! I just updated it with a new link (https://join.slack.com/t/zendesk-volunteer/shared_invite/enQtNDczNTM5MzEwNjQwLTNmMmI3NzdlNjg4ODc4ZDFmYzBkODljZWQ2NmY0OWM3NDliOTdlMzAzOTdkZTBiYjBmMmQ3ZGFjOTFlMjdlNDk)

Let me know if this works now @nick-f ?

**Comment by nick-f** [comment]
Thanks @roseleaf ! Looks like it's working in a different browser even after I've signed up using it once already. Looks like you've already updated the README, so closing this out 🙂
