### ISSUE TITLE
As an Admin I expect the UI to update when I change a user's office

### ISSUE THREAD

**Issue by ThuTrinh** [zendesk/volunteer_portal#195]
## Steps to reproduce
1. as an admin navigate to the user profile edit page
2. change the office and press the save button

## Expected behaviour
The UI should update with the new office without clearing cache. i.e. the office name in the user profile in top right corner and user profile screen.

## Actual behaviour
The UI displays the previous office name. A hard refresh is required to get the new changes.

![before](https://user-images.githubusercontent.com/3032977/63991423-194cb300-cb2b-11e9-877d-8fee141af1a6.gif)

**Comment by samzx** [comment]
Well done! 🎉  closed as it is now resolved!
