### ISSUE TITLE
Pagination for My Events Tables

### ISSUE THREAD

**Issue by samzx** [zendesk/volunteer_portal#219]
For those who've done lots of hours, the tables can get pretty lengthy. Would be awesome to use pagination to keep the page size smaller.

**Comment by danielharvilik** [comment]
Hey!, is it available ?

**Comment by samzx** [comment]
Hey @danielharvilik, yes, feel free tackle this one 🙂

**Comment by jliclaire** [comment]
Hi @danielharvilik, are you working on this issue?

**Comment by sunstryder** [comment]
Hey team, Just realised I incidentally fixed this in https://github.com/zendesk/volunteer_portal/pull/257
