### ISSUE TITLE
Individual events: Dates not rendered correctly

### ISSUE THREAD

**Issue by timotheeg** [zendesk/volunteer_portal#22]
Possibly a Timezone management issue. I'm in the Singapore office (GMT+8) and the dates displayed in the  event list are one day prior to the date I selected in the UI.

![image](https://user-images.githubusercontent.com/935223/41825781-8af3be28-7856-11e8-8892-fbae6258ef4c.png)

**Comment by xuebingli** [comment]
https://github.com/zendesk/volunteer_portal/blob/0d23a1fc64346ec0802cc1b44861e000c8024526/app/graph/types/mutation_graph_type.rb#L63
