### ISSUE TITLE
Triple avatar when signing up bug

### ISSUE THREAD

**Issue by samzx** [zendesk/volunteer_portal#224]
When signing up to events, the UI make three avatars appear to have signed up

> I signed up for an event and it decided I was worth 3 regular volunteers :wink:
(Refreshing showed correct results, so presumably just a client-side bug)

> still seeing a triple sign up happen when I click ‘join’ on an event. It’s not signing me up three times, just bizarre UI behaviour. After this all events dispeared from the month I was viewing too. I had to do a refresh

References (Zendesk Only):
https://zendesk.slack.com/archives/GBTLTQLQN/p1569216217001400
https://zendesk.slack.com/archives/GBTLTQLQN/p1571000067000100

**Comment by samzx** [comment]
another report:
https://zendesk.slack.com/archives/GBTLTQLQN/p1572827398000100

**Comment by kayison** [comment]
This bug was introduced when `inverse_by` was added to https://github.com/zendesk/volunteer_portal/blob/8ee7427c71ea3df350656b8b32bbb8156737c03f/app/models/event.rb#L4

I'm not exactly sure why it's causing the duplicates yet though
