### ISSUE TITLE
Investigate/Fix Jest Snapshot tests

### ISSUE THREAD

**Issue by ThuTrinh** [zendesk/volunteer_portal#227]
We use Jest to perform snapshot tests in our CI pipeline. When we update our view components we need to also update our snapshots locally and commit them.

Jest seems to generate different snapshots when running locally compared to that in CI. This causes failing test and blocks merging.

Perhaps look into how Jest generates these snapshots. There might be some settings that differ between environments.

**Comment by samzx** [comment]
https://github.com/zendesk/volunteer_portal/pull/231 closes this
