### ISSUE TITLE
Make delete events transactional

### ISSUE THREAD

**Issue by samzx** [zendesk/volunteer_portal#254]
Currently, if you delete an event, there's a possibility that it doesn't delete the sign up. I think it's because it's not transactional - someone please double check.

This causes errors when the signup query tries to fetch an event that doesn't exist!

We should fix this.

**Comment by ThuTrinh** [comment]
Had a conversation with @samzx @kennethc regarding hard deletes of data. 
We decided that it is undesirable to perform hard deletes on events and related data for the following reasons:
1. audit data will be lost
2. historical time spent data will be inaccurate/lost.

Instead we are going to implement soft deletions. Where GDPR is concerned, this will go through a different flow which will delete all data related to a particular user.

**Comment by ThuTrinh** [comment]
Current ERD
![Volunteer Portal](https://user-images.githubusercontent.com/3032977/70115456-d7945100-16b3-11ea-9d7c-086e88d12f01.png)

**Comment by ThuTrinh** [comment]
I did a scan of the codebase and github repo, and I am pretty sure the `volunteers` and `events_volunteers` tables are not being used at all. Looking at the git history, it looks like they were created early on. I suspect things got complicated and a decision was made to use the `users` and `signup` tables instead.

I want to delete these tables. What do you think @samzx ?

**Comment by samzx** [comment]
I'm not sure if there's any data stored in those tables there from the previous life, we should make sure we keep those for records.  I'm happy to remove the create schemas if they're not used. Thoughts?

**Comment by samzx** [comment]
just had a thought - check the foreign key constraints for cascading too

**Comment by ThuTrinh** [comment]
> I'm not sure if there's any data stored in those tables there from the previous life, we should make sure we keep those for records. I'm happy to remove the create schemas if they're not used. Thoughts?

I checked production and `sessions` seems to be in use still (has fresh data). However the `volunteers` and `event_volunteers` table are empty. I think it's safe to remove these two tables ina migration script to avoid confusion in the future.
