### ISSUE TITLE
Filter by office is broken in the admin page for events 

### ISSUE THREAD

**Issue by roseleaf** [zendesk/volunteer_portal#26]
This is a production bug reported in our internal instance at https://volunteerhelp.zendesk.com/agent/tickets/57

> When I am on the admin side of things looking at the events page, I am unable to filter by office. on the 'All' page I am able to see everything but when I try to filter to just SF no events appear

**Comment by xuebingli** [comment]
Closed by https://github.com/zendesk/volunteer_portal/pull/39.
