### ISSUE TITLE
Multiple event type fields.

### ISSUE THREAD

**Issue by samzx** [zendesk/volunteer_portal#265]
It'd be nice to have generic fields to categories events. Currently we have one "Event Type" field. We should have multiple event type fields.

Have a title, admins can choose the field name ie: "Event Type" or "Focus Area"
and they both would share a similar structure where admins can add that type, users would need to select an option for these two. This is helpful for reporting in specific target areas like "Education & Local Neighbourhoods" or "Wellbeing & Families" or "Eduction & Families" etc.

**Comment by jliclaire** [comment]
add validation to frontend to make sure at least one tag is selected
