### ISSUE TITLE
Improve Individual Event Dropdown

### ISSUE THREAD

**Issue by adam-hart** [zendesk/volunteer_portal#277]
The Organization drop down for Individual Event creation is very difficult to use.  It's not searchable or sorted, and it's massive, making it really really hard to find the Organization you want.

**Comment by samzx** [comment]
https://github.com/zendesk/volunteer_portal/pull/273 should have fixed this, please confirm :) 

It likely broke after the material-ui version bump

**Comment by samzx** [comment]
Should be fixed now 😄
