### ISSUE TITLE
Change the goal / milestones on the dashboard

### ISSUE THREAD

**Issue by samzx** [zendesk/volunteer_portal#283]
~Change the goal on the dashboard from 12 hours to 6 hours with 2 hours being each of the milestone.~ Potential to make it configurable (if it isn't already?)

![image](https://user-images.githubusercontent.com/27116427/71855061-23fc0200-3134-11ea-9b4d-43c3085cb13f.png)

**Comment by samzx** [comment]
Spotted here, seems to be an easy fix.

https://github.com/zendesk/volunteer_portal/pull/301/files#diff-186b5f1ba11b52cbc110f49d487ac5e6R12-R16

**Comment by samzx** [comment]
We'll need to make it configurable for admins. #308 changes it to 6 hours.

**Comment by kennethc** [comment]
This issue is solved. Feature request is tracked in #214
