### ISSUE TITLE
fix the styling on the address autocomplete fields

### ISSUE THREAD

**Issue by craig-day** [zendesk/volunteer_portal#3]
The menu that shows up should not push content down.

![](https://camo.githubusercontent.com/575b8b061bfb564a30ce55c8fefb24811e918a38/68747470733a2f2f636f6e74656e742e73637265656e636173742e636f6d2f75736572732f434461792e7a656e6465736b2f666f6c646572732f4a696e672f6d656469612f32333132303636302d316234342d343338362d393338652d3437313233356639353533642f30303030303031312e706e67)

**Comment by xuebingli** [comment]
Dup of #7
