### ISSUE TITLE
Fix Top Volunteers on Dashboard

### ISSUE THREAD

**Issue by danielbreves** [zendesk/volunteer_portal#53]
### References
* Ticket 76

**Comment by danielbreves** [comment]
It seems like this query is still not returning sorted results: https://github.com/zendesk/volunteer_portal/blob/4963611e1590aafbd8a57fec4b48c024aba1ae7c/app/graph/resolvers/user_resolver.rb#L85-L115. It may still not be completely accurate.

**Comment by timbertson-zd** [comment]
We came up with a modified SQL that works, but haven't started the work to represent it in activerecord yet:

```
SELECT
  "users".id, "users".first_name, users.last_name,
  event_durations.total, individual_event_durations.total,
  COALESCE(individual_event_durations.total,0) + COALESCE(event_durations.total,0) as total_duration
  from users
  left outer join (
    select users.id as user_id, 
    SUM((EXTRACT(EPOCH FROM "events"."ends_at") - EXTRACT(EPOCH FROM "events"."starts_at")) / 60) as total
    FROM "users" 
    INNER JOIN "signups" ON "signups"."user_id" = "users"."id" 
    INNER JOIN "events" ON "events"."id" = "signups"."event_id" 
      AND ("events"."starts_at" > '2017-12-31 13:00:00') 
      AND ("events"."starts_at" < '2018-12-31 13:00:00') 
    GROUP BY users.id
  ) as event_durations
  on event_durations.user_id = users.id

  left outer join (
    select users.id as user_id, 
    SUM("individual_events"."duration") as total
    FROM "users" 
    INNER JOIN "individual_events" ON "individual_events"."user_id" = "users"."id" 
      AND "individual_events"."date" > '2018-01-01' 
      AND "individual_events"."date" < '2019-01-01' 
    GROUP BY "users"."id"
  ) as individual_event_durations
  ON event_durations.user_id = individual_event_durations.user_id
  and users.id = event_durations.user_id

WHERE "users"."deleted_at" IS NULL
ORDER BY total_duration
;
```

The basic idea is two independent queries where you get one row per user (even if the duration is 0), and then join them on user.id and sum the two types of durations.

**Comment by timbertson-zd** [comment]
(we also noticed that the start / end conditions are a little inconsistent between the two types, which is another bug)

**Comment by screamish** [comment]
From a discussion with @xuebingli @kennethc just now:

It seems like a query structured at its core around "users" inner joined to a union of the two event tables could solve this. Sadly, ActiveRecord doesn't seem to support unions so it would still have to be hand-rolled SQL.

It's also possibly time to look at refactoring the database model to represent both event types as one core table with specialised extra tables for their custom attributes.

**Comment by kennethc** [comment]
We have started populating `events.duration` again in #158 and added a task in #168 to backfill the events without duration. This is done so we can simplify the way we query for the duration for all the users, eg:
```
select t.user_id, sum(t.duration) 
from (
    (select s.user_id, e.duration from signups s join events e on s.event_id=e.id) 
    union 
    (select i.user_id, i.duration from individual_events i)
) t 
group by 1
order by 2 desc
limit 10;
```

@xuebingli has suggested that we should perhaps have a graphql endpoint focused on returning the top volunteer hours, then fetch the user data (ie: names) individually. This means we can use the example query above with minimal changes.

We will likely need to have some logic to inject the conditions into the query to filter by office and datetime. To deal with the `union`, we can refer to these sources:
https://stackoverflow.com/questions/6686920/activerecord-query-union
https://thepugautomatic.com/2014/08/union-with-active-record/

**Comment by kennethc** [comment]
This query will get us the correct sum of volunteering minutes.
```
select t.user_id, sum(t.duration) 
from (
    (
        select s.user_id, e.duration 
        from signups s 
        join events e on s.event_id=e.id 
        join users u on s.user_id=u.id 
        where e.starts_at between '2018-12-31 13:00:00' and '2019-07-31 23:59:59'
        and u.office_id=6
    ) 
    union all
    (
        select i.user_id, i.duration 
        from individual_events i 
        join users u on i.user_id=u.id 
        where i.date between '2018-12-31 13:00:00' and '2019-07-31 23:59:59'
        and u.office_id=6
    )
) t 
group by 1
order by 2 desc
limit 10;
```

**Comment by kennethc** [comment]
Issue is resolved.
