### ISSUE TITLE
Prompt every user to set default office via an IPM

### ISSUE THREAD

**Issue by jpandl19** [zendesk/volunteer_portal#67]
CSR is having a lot of issues with users having the wrong default office setup. Most people are categorized under "Remote" (since this is what every new user defaults to initially). This means that CSR has to go through each month and manually change the users to their correct office.

We need a one-time in-product message to prompt all current `volunteer_portal` users to update their default office.

Related issue: #66

**Comment by samzx** [comment]
closed by #293
