### ISSUE TITLE
Improved available spots indication on the events page

### ISSUE THREAD

**Issue by dadah89** [zendesk/volunteer_portal#69]
E.g. http://volunteer.zende.sk/portal/events/1927

Someone sent me the link above, and when I clicked, had trouble finding the available spots, went back to the calendar to confirm it.

Turns out the bar wasn't full, but I didn't notice it (I'd also need to infer that the space left meant 1):
<img width="677" alt="screen shot 2018-09-13 at 11 25 20 am" src="https://user-images.githubusercontent.com/697824/45508635-25890600-b74a-11e8-8441-beab9821a3d0.png">

Small suggestion, changing the number to something like 24/25 would make pretty obvious how many spots are available.

**Comment by samzx** [comment]
solved by #153 thanks for the issue!
