### ISSUE TITLE
sorting in dashboard broken

### ISSUE THREAD

**Issue by azaiszen** [zendesk/volunteer_portal#70]
currently not sorting from highest to lowest

![](https://d3vv6lp55qjaqc.cloudfront.net/items/361U0Y2B1T1v2K2A0j2q/Image%202018-09-20%20at%2011.09.09%20am.png)

**Comment by rshokrizadeh** [comment]
Can we close this off since the client side fix is out? Or is there more that can be done here?

**Comment by xuebingli** [comment]
The sorting should be done on the server side for correctness. Client side sorting does not guarantee only top volunteers are returned by the server side.

**Comment by kennethc** [comment]
This is related to https://github.com/zendesk/volunteer_portal/issues/53

**Comment by kennethc** [comment]
Once #53 is deployed, sorting should be correct. Which means we should be able to revert https://github.com/zendesk/volunteer_portal/pull/81 as that would no longer be needed.

**Comment by kennethc** [comment]
#53 is resolved and closed. Should we keep the sorting logic here, or should the frontend rely on the backend returning the correct sort order when requested?

Technically, the frontend does request the sort in the graphql, so this is an explicit behaviour requested of the backend. We should remove this additional sorting logic in the frontend.
