### ISSUE TITLE
new user, set location option

### ISSUE THREAD

**Issue by azaiszen** [zendesk/volunteer_portal#75]
when someone logs into the portal for the first time, lightbox to appear to get the user to set their office location. also in this prompt a reminder that if you are visiting an office for onboarding that you need to set it to your home office after onboarding volunteering etc. this is in lieu of workday integration (which would fix so many tings!)

**Comment by jpandl19** [comment]
This looks like a dup of https://github.com/zendesk/volunteer_portal/issues/66 😄 
Has a couple more details that would be worth adding to that issue though

**Comment by azaiszen** [comment]
@jpandl19 my bad! I'm new at this - can you tell? I see that I can manually change the users location, but don't want to do so because it's an open text field - so added a request to also have this changed to a dropdown so it doesn't break the internet
